version: '3.1'

services:
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: velo
      MYSQL_USER: velo
      MYSQL_PASSWORD: velo
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  front:
    build: .
    restart: always
    volumes:
      - .:/var/www/
    ports:
      - "8000:80"
    command: >
      bash -c "
      /usr/local/bin/wait-for-it.sh db:3306 --timeout=30 -- echo 'db is up' &&
      chmod -R 777 /var/www/public/images &&
      composer install &&
      composer require doctrine/doctrine-fixtures-bundle --dev &&
      npm install &&
      npm run build &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php bin/console doctrine:fixtures:load --no-interaction &&
      apache2-foreground"

    depends_on:
      - db
volumes:
  db_data:
