controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
errors:
    path: /error
    controller: App\Controller\ErrorController::showErrorPage

app_diagnostic_elements_by_type:
    path: '/diagnostic/elements/{id}'
    controller: 'App\Controller\DiagnosticController::diagnosticElementsByType'

autocomplete:
    path: '/autocomplete'
    controller: 'App\Controller\AutoCompleteController::autocompleteProprietaires'
    methods: [GET]
